### ISSUE TITLE
Please add a readme specifying where to install everything.

### ISSUE THREAD

**Issue by AJMansfield** [Crzyrndm/DynamicControls#1]
Since it doesn't appear to be just a simple 'drop this folder in your GameData directory' install, could you add a little bit of info about exactly where to put everything?

**Comment by Crzyrndm** [comment]
There is a GameData folder inside the zip. You merge that with KSP's GameData folder (or go one step deeper and place the dynamic Controls folder in KSP GameData. Same effect)
